// =============================================================================
//  AUTO-GENERATED by ExportGameData.py. DO NOT HAND-EDIT.
//  Regenerate from Ghidra after relabeling. Program: AtGameSettingsScreen
// =============================================================================
#pragma once
#include "Include/Global/GlobalData.h"


// =============================================================================
//  AtGameSettingsScreen-SPECIFIC DATA SYMBOLS (REL, at/above 0x803CD310)
// =============================================================================

#define switchdataD_806d7118 VAR_ADDRESS(void *, 0x806D7118)
#define switchdataD_806d7140 VAR_ADDRESS(void *, 0x806D7140)
#define pCurrentScreenControlFunction VAR_ADDRESS(undefined *, 0x806D7178)
#define switchdataD_806d7664 VAR_ADDRESS(void *, 0x806D7664)
#define switchdataD_806d7680 VAR_ADDRESS(void *, 0x806D7680)
#define switchdataD_806d769c VAR_ADDRESS(void *, 0x806D769C)
#define switchdataD_806d76b8 VAR_ADDRESS(void *, 0x806D76B8)
#define switchdataD_806d76d4 VAR_ADDRESS(void *, 0x806D76D4)
#define switchdataD_806d7700 VAR_ADDRESS(void *, 0x806D7700)
#define switchdataD_806d7728 VAR_ADDRESS(void *, 0x806D7728)
#define switchdataD_806d7eec VAR_ADDRESS(void *, 0x806D7EEC)
#define switchdataD_806d7f10 VAR_ADDRESS(void *, 0x806D7F10)
#define switchdataD_806d7f3c VAR_ADDRESS(void *, 0x806D7F3C)
#define switchdataD_806d7f60 VAR_ADDRESS(void *, 0x806D7F60)
#define switchdataD_806d7f84 VAR_ADDRESS(void *, 0x806D7F84)
#define switchdataD_806d7fa8 VAR_ADDRESS(void *, 0x806D7FA8)
#define switchdataD_806d7fd4 VAR_ADDRESS(void *, 0x806D7FD4)
#define switchdataD_806d7ff8 VAR_ADDRESS(void *, 0x806D7FF8)
#define switchdataD_806d801c VAR_ADDRESS(void *, 0x806D801C)
#define cursorToStadIDMapping ARRAY_1D_ADDRESS(enumStadiumName, 6, 0x806D834C)
#define switchdataD_806d85d4 VAR_ADDRESS(void *, 0x806D85D4)
#define switchdataD_806d89f4 VAR_ADDRESS(void *, 0x806D89F4)
#define switchdataD_806d9b9c VAR_ADDRESS(void *, 0x806D9B9C)
#define switchdataD_806dbbf4 VAR_ADDRESS(void *, 0x806DBBF4)
#define switchdataD_806dbc28 VAR_ADDRESS(void *, 0x806DBC28)
#define switchdataD_806dbc44 VAR_ADDRESS(void *, 0x806DBC44)
#define switchdataD_806e78a4 VAR_ADDRESS(void *, 0x806E78A4)
#define switchdataD_806e78dc VAR_ADDRESS(void *, 0x806E78DC)
#define switchdataD_806e7908 VAR_ADDRESS(void *, 0x806E7908)
#define switchdataD_806e7934 VAR_ADDRESS(void *, 0x806E7934)
#define switchdataD_806e7960 VAR_ADDRESS(void *, 0x806E7960)
#define switchdataD_806e7984 VAR_ADDRESS(void *, 0x806E7984)
#define switchdataD_806e7b94 VAR_ADDRESS(void *, 0x806E7B94)
#define switchdataD_806e7c2c VAR_ADDRESS(void *, 0x806E7C2C)
#define switchdataD_806e7cc4 VAR_ADDRESS(void *, 0x806E7CC4)
#define switchdataD_806e7d5c VAR_ADDRESS(void *, 0x806E7D5C)
#define switchdataD_806e7df4 VAR_ADDRESS(void *, 0x806E7DF4)
#define switchdataD_806e7e8c VAR_ADDRESS(void *, 0x806E7E8C)
#define switchdataD_806e7f24 VAR_ADDRESS(void *, 0x806E7F24)
#define switchdataD_806e7fbc VAR_ADDRESS(void *, 0x806E7FBC)
#define switchdataD_806e8054 VAR_ADDRESS(void *, 0x806E8054)
#define switchdataD_806e80ec VAR_ADDRESS(void *, 0x806E80EC)
#define switchdataD_806e8184 VAR_ADDRESS(void *, 0x806E8184)
#define switchdataD_806e821c VAR_ADDRESS(void *, 0x806E821C)
#define switchdataD_806e82b4 VAR_ADDRESS(void *, 0x806E82B4)
#define switchdataD_806e834c VAR_ADDRESS(void *, 0x806E834C)
#define switchdataD_806e83e4 VAR_ADDRESS(void *, 0x806E83E4)
#define switchdataD_806e847c VAR_ADDRESS(void *, 0x806E847C)
#define switchdataD_806e8514 VAR_ADDRESS(void *, 0x806E8514)
#define switchdataD_806e85ac VAR_ADDRESS(void *, 0x806E85AC)
#define switchdataD_806e8644 VAR_ADDRESS(void *, 0x806E8644)
#define switchdataD_806e86dc VAR_ADDRESS(void *, 0x806E86DC)
#define switchdataD_806e8774 VAR_ADDRESS(void *, 0x806E8774)
#define switchdataD_806e880c VAR_ADDRESS(void *, 0x806E880C)
#define switchdataD_806e88a4 VAR_ADDRESS(void *, 0x806E88A4)
#define switchdataD_806e893c VAR_ADDRESS(void *, 0x806E893C)
#define switchdataD_806e89d4 VAR_ADDRESS(void *, 0x806E89D4)
#define switchdataD_806e8a6c VAR_ADDRESS(void *, 0x806E8A6C)
#define switchdataD_806e8b04 VAR_ADDRESS(void *, 0x806E8B04)
#define switchdataD_806e8b9c VAR_ADDRESS(void *, 0x806E8B9C)
#define switchdataD_806e8c34 VAR_ADDRESS(void *, 0x806E8C34)
#define switchdataD_806e8ccc VAR_ADDRESS(void *, 0x806E8CCC)
#define switchdataD_806e8d64 VAR_ADDRESS(void *, 0x806E8D64)
#define switchdataD_806e8dfc VAR_ADDRESS(void *, 0x806E8DFC)
#define switchdataD_806e8e94 VAR_ADDRESS(void *, 0x806E8E94)
#define switchdataD_806e8eb8 VAR_ADDRESS(void *, 0x806E8EB8)
#define switchdataD_806e8f50 VAR_ADDRESS(void *, 0x806E8F50)
#define switchdataD_806e8fe8 VAR_ADDRESS(void *, 0x806E8FE8)
#define switchdataD_806e9080 VAR_ADDRESS(void *, 0x806E9080)
#define switchdataD_806e9118 VAR_ADDRESS(void *, 0x806E9118)
#define switchdataD_806e92b4 VAR_ADDRESS(void *, 0x806E92B4)
#define switchdataD_806e92f8 VAR_ADDRESS(void *, 0x806E92F8)
#define switchdataD_806e9344 VAR_ADDRESS(void *, 0x806E9344)
#define switchdataD_806e9390 VAR_ADDRESS(void *, 0x806E9390)
#define switchdataD_806e93b0 VAR_ADDRESS(void *, 0x806E93B0)
#define switchdataD_806e93d0 VAR_ADDRESS(void *, 0x806E93D0)
#define switchdataD_806e9404 VAR_ADDRESS(void *, 0x806E9404)
#define switchdataD_806e9438 VAR_ADDRESS(void *, 0x806E9438)
#define switchdataD_806e9454 VAR_ADDRESS(void *, 0x806E9454)
#define switchdataD_806e9470 VAR_ADDRESS(void *, 0x806E9470)
#define switchdataD_806e94ac VAR_ADDRESS(void *, 0x806E94AC)
#define switchdataD_806e9d2c VAR_ADDRESS(void *, 0x806E9D2C)
#define switchdataD_806ea3b8 VAR_ADDRESS(void *, 0x806EA3B8)
#define switchdataD_806ea40c VAR_ADDRESS(void *, 0x806EA40C)
#define switchdataD_806ea478 VAR_ADDRESS(void *, 0x806EA478)
#define switchdataD_806f6430 VAR_ADDRESS(void *, 0x806F6430)
#define switchdataD_806f68e4 VAR_ADDRESS(void *, 0x806F68E4)
#define switchdataD_806f78c4 VAR_ADDRESS(void *, 0x806F78C4)
#define switchdataD_806f78e0 VAR_ADDRESS(void *, 0x806F78E0)
#define switchdataD_806f7934 VAR_ADDRESS(void *, 0x806F7934)
#define switchdataD_806f79cc VAR_ADDRESS(void *, 0x806F79CC)
#define switchdataD_806f7a64 VAR_ADDRESS(void *, 0x806F7A64)
#define switchdataD_806f7afc VAR_ADDRESS(void *, 0x806F7AFC)
#define switchdataD_806f7b94 VAR_ADDRESS(void *, 0x806F7B94)
#define switchdataD_80700788 VAR_ADDRESS(void *, 0x80700788)
#define switchdataD_807007a8 VAR_ADDRESS(void *, 0x807007A8)
#define switchdataD_80700810 VAR_ADDRESS(void *, 0x80700810)
#define switchdataD_80700854 VAR_ADDRESS(void *, 0x80700854)
#define switchdataD_807008a0 VAR_ADDRESS(void *, 0x807008A0)
#define switchdataD_807008dc VAR_ADDRESS(void *, 0x807008DC)
#define switchdataD_80700920 VAR_ADDRESS(void *, 0x80700920)
#define switchdataD_80700980 VAR_ADDRESS(void *, 0x80700980)
#define switchdataD_807009b0 VAR_ADDRESS(void *, 0x807009B0)
#define switchdataD_807009d4 VAR_ADDRESS(void *, 0x807009D4)
#define switchdataD_80700a6c VAR_ADDRESS(void *, 0x80700A6C)
#define switchdataD_80700b04 VAR_ADDRESS(void *, 0x80700B04)
#define switchdataD_80700b9c VAR_ADDRESS(void *, 0x80700B9C)
#define switchdataD_80700c34 VAR_ADDRESS(void *, 0x80700C34)
#define switchdataD_80700ccc VAR_ADDRESS(void *, 0x80700CCC)
#define switchdataD_80700d64 VAR_ADDRESS(void *, 0x80700D64)
#define switchdataD_80700dfc VAR_ADDRESS(void *, 0x80700DFC)
#define switchdataD_80700e94 VAR_ADDRESS(void *, 0x80700E94)
#define switchdataD_80700f2c VAR_ADDRESS(void *, 0x80700F2C)
#define switchdataD_80700fc4 VAR_ADDRESS(void *, 0x80700FC4)
#define switchdataD_8070105c VAR_ADDRESS(void *, 0x8070105C)
#define switchdataD_807010f4 VAR_ADDRESS(void *, 0x807010F4)
#define switchdataD_8070118c VAR_ADDRESS(void *, 0x8070118C)
#define switchdataD_8070138c VAR_ADDRESS(void *, 0x8070138C)
#define BYTE_ARRAY_807023e4 ARRAY_1D_ADDRESS(byte, 2, 0x807023E4)
#define switchdataD_80704884 VAR_ADDRESS(void *, 0x80704884)
#define switchdataD_80704960 VAR_ADDRESS(void *, 0x80704960)
#define switchdataD_807049b4 VAR_ADDRESS(void *, 0x807049B4)
#define switchdataD_80705330 VAR_ADDRESS(void *, 0x80705330)
#define switchdataD_8070562c VAR_ADDRESS(void *, 0x8070562C)
#define switchdataD_807069ac VAR_ADDRESS(void *, 0x807069AC)
#define switchdataD_80706f2c VAR_ADDRESS(void *, 0x80706F2C)
#define switchdataD_80706fec VAR_ADDRESS(void *, 0x80706FEC)
#define switchdataD_80707018 VAR_ADDRESS(void *, 0x80707018)
#define mainMenuSwitch VAR_ADDRESS(undefined1, 0x80741800)
#define INT_ARRAY_80750bf0 ARRAY_1D_ADDRESS(int, 4, 0x80750BF0)
#define cursorPositionInt ARRAY_1D_ADDRESS(int, 2, 0x80750C00)
#define characterIDOfWhereCursorIs_FF_IfNotSelectable_ ARRAY_1D_ADDRESS(int, 2, 0x80750C10)
#define cursorPos_stadSelect VAR_ADDRESS(undefined4, 0x80750C34)
#define positionCursorPosition ARRAY_1D_ADDRESS(int, 2, 0x80750C48)
#define rosterSpotChosen ARRAY_1D_ADDRESS(int, 2, 0x80750C50)
#define charIDOfBottomCursor ARRAY_1D_ADDRESS(int, 2, 0x80750C68)
#define frameCounterToChangeScreens_ VAR_ADDRESS(undefined1, 0x80750C7E)
#define okButtonSelectable ARRAY_1D_ADDRESS(byte, 2, 0x80750C7F)
#define BYTE_ARRAY_80750c83 ARRAY_1D_ADDRESS(byte, 2, 0x80750C83)
#define BYTE_ARRAY_80750c85 ARRAY_1D_ADDRESS(byte, 2, 0x80750C85)
#define cursorOnCharacterGridInd ARRAY_1D_ADDRESS(byte, 2, 0x80750C89)
#define BYTE_ARRAY_80750c8b ARRAY_1D_ADDRESS(byte, 2, 0x80750C8B)
#define showingPlayerProfileInd ARRAY_1D_ADDRESS(byte, 2, 0x80750C8D)
#define playerProfilePageNum ARRAY_1D_ADDRESS(byte, 2, 0x80750C8F)
#define playerProfileOpenInd2_ ARRAY_1D_ADDRESS(byte, 2, 0x80750C91)
#define BYTE_ARRAY_80750c9a ARRAY_1D_ADDRESS(byte, 2, 0x80750C9A)
#define backOutOfTeamSelectScreenInd VAR_ADDRESS(undefined1, 0x80750C9E)
#define stadiumSelectedInd VAR_ADDRESS(undefined1, 0x80750CA0)
#define BYTE_ARRAY_80750ca1 ARRAY_1D_ADDRESS(byte, 2, 0x80750CA1)
#define BYTE_ARRAY_80750ca9 ARRAY_1D_ADDRESS(byte, 2, 0x80750CA9)
#define bothCapsSelectedInd VAR_ADDRESS(undefined1, 0x80751894)
#define captainSelectStruct VAR_ADDRESS(structCaptainSelectScreen, 0x80751898)
#define nCursorsAvailable_ VAR_ADDRESS(undefined1, 0x807518C5)
#define teamReadyInd ARRAY_1D_ADDRESS(byte, 2, 0x807518C6)
#define captainAnimationNotOccuringInd ARRAY_1D_ADDRESS(byte, 2, 0x807518D8)
#define BYTE_ARRAY_807518da ARRAY_1D_ADDRESS(byte, 2, 0x807518DA)
#define BYTE_ARRAY_807518de ARRAY_1D_ADDRESS(byte, 2, 0x807518DE)
#define titleScreenRelated VAR_ADDRESS(enum_titleScreenCode, 0x80A81A24)

// =============================================================================
//  AtGameSettingsScreen-SPECIFIC PLAIN LABELS (REL)
// =============================================================================

#define switchD_ADDR_8063f93c 0x8063F93C
#define switchD_ADDR_8063fa58 0x8063FA58
#define switchD_ADDR_80640688 0x80640688
#define switchD_ADDR_80640910 0x80640910
#define switchD_ADDR_80640e8c 0x80640E8C
#define switchD_ADDR_80641000 0x80641000
#define switchD_ADDR_806412b8 0x806412B8
#define switchD_ADDR_806418b0 0x806418B0
#define switchD_ADDR_806418e8 0x806418E8
#define switchD_ADDR_80642818 0x80642818
#define switchD_ADDR_80642970 0x80642970
#define switchD_ADDR_80642b00 0x80642B00
#define switchD_ADDR_80642c94 0x80642C94
#define switchD_ADDR_806449a0 0x806449A0
#define switchD_ADDR_80644b60 0x80644B60
#define switchD_ADDR_80644d18 0x80644D18
#define switchD_ADDR_80644edc 0x80644EDC
#define noLeft_CheckY_ADDR 0x8064FBF4
#define noY_CheckZ_ADDR 0x8064FDB4
#define noZ_CheckRight_ADDR 0x80650014
#define noRight_ABOrDirection_ADDR 0x8065011C
#define goToEndOfFun_ADDR 0x80650130
#define switchD_ADDR_80650178 0x80650178
#define switchD_ADDR_80650770 0x80650770
#define switchD_ADDR_80652054 0x80652054
#define deselectCaptain_ADDR 0x80655428
#define switchD_ADDR_80658dcc 0x80658DCC
#define switchD_ADDR_8065a3ec 0x8065A3EC
#define switchD_ADDR_8065a690 0x8065A690
#define switchD_ADDR_8065a910 0x8065A910
#define switchD_ADDR_8065c510 0x8065C510
#define switchD_ADDR_8065f3f4 0x8065F3F4
#define switchD_ADDR_8065f8c8 0x8065F8C8
#define switchD_ADDR_8065fd64 0x8065FD64
#define switchD_ADDR_8065fe14 0x8065FE14
#define switchD_ADDR_80660238 0x80660238
#define switchD_ADDR_80664b30 0x80664B30
#define switchD_ADDR_806653b8 0x806653B8
#define switchD_ADDR_8066594c 0x8066594C
#define switchD_ADDR_80665d58 0x80665D58
#define switchD_ADDR_806661a0 0x806661A0
#define switchD_ADDR_80667598 0x80667598
#define switchD_ADDR_80667a30 0x80667A30
#define switchD_ADDR_80667f84 0x80667F84
#define switchD_ADDR_80668350 0x80668350
#define switchD_ADDR_8066896c 0x8066896C
#define switchD_ADDR_80669420 0x80669420
#define switchD_ADDR_8066a524 0x8066A524
#define switchD_ADDR_8066a96c 0x8066A96C
#define switchD_ADDR_8066b008 0x8066B008
#define switchD_ADDR_8066c040 0x8066C040
#define switchD_ADDR_8066c1bc 0x8066C1BC
#define switchD_ADDR_8066d8b8 0x8066D8B8
#define switchD_ADDR_8066dccc 0x8066DCCC
#define switchD_ADDR_8066e18c 0x8066E18C
#define switchD_ADDR_8066e7f8 0x8066E7F8
#define switchD_ADDR_8066eb64 0x8066EB64
#define switchD_ADDR_8066ecb4 0x8066ECB4
#define switchD_ADDR_8066ede8 0x8066EDE8
#define switchD_ADDR_8066ef38 0x8066EF38
#define switchD_ADDR_8066f1a4 0x8066F1A4
#define switchD_ADDR_8066f488 0x8066F488
#define switchD_ADDR_8066f7c0 0x8066F7C0
#define switchD_ADDR_8066f97c 0x8066F97C
#define switchD_ADDR_8066fd34 0x8066FD34
#define switchD_ADDR_8066fe68 0x8066FE68
#define switchD_ADDR_8066ffe0 0x8066FFE0
#define switchD_ADDR_80670338 0x80670338
#define switchD_ADDR_806720ac 0x806720AC
#define switchD_ADDR_806722b0 0x806722B0
#define switchD_ADDR_806744e4 0x806744E4
#define switchD_ADDR_80674afc 0x80674AFC
#define switchD_ADDR_80675838 0x80675838
#define switchD_ADDR_80675dec 0x80675DEC
#define switchD_ADDR_80676aa4 0x80676AA4
#define switchD_ADDR_80678a9c 0x80678A9C
#define switchD_ADDR_80679fdc 0x80679FDC
#define switchD_ADDR_8067ae58 0x8067AE58
#define switchD_ADDR_8067b60c 0x8067B60C
#define switchD_ADDR_8067bb34 0x8067BB34
#define switchD_ADDR_8067be04 0x8067BE04
#define switchD_ADDR_8067c694 0x8067C694
#define switchD_ADDR_8067c948 0x8067C948
#define switchD_ADDR_8067d128 0x8067D128
#define switchD_ADDR_8067d45c 0x8067D45C
#define switchD_ADDR_8067fdc4 0x8067FDC4
#define switchD_ADDR_80681858 0x80681858
#define switchD_ADDR_80681d38 0x80681D38
#define switchD_ADDR_80682b14 0x80682B14
#define switchD_ADDR_8068dcbc 0x8068DCBC
#define switchD_ADDR_8069175c 0x8069175C
#define switchD_ADDR_80693a84 0x80693A84
#define switchD_ADDR_80693d48 0x80693D48
#define switchD_ADDR_80694bbc 0x80694BBC
#define switchD_ADDR_80694d44 0x80694D44
#define switchD_ADDR_80694ec0 0x80694EC0
#define switchD_ADDR_806950c0 0x806950C0
#define switchD_ADDR_80695248 0x80695248
#define switchD_ADDR_80697950 0x80697950
#define switchD_ADDR_80699304 0x80699304
#define switchD_ADDR_8069a080 0x8069A080
#define switchD_ADDR_8069a8ac 0x8069A8AC
#define switchD_ADDR_8069b684 0x8069B684
#define switchD_ADDR_8069bc28 0x8069BC28
#define switchD_ADDR_8069c34c 0x8069C34C
#define switchD_ADDR_8069cd30 0x8069CD30
#define switchD_ADDR_8069d274 0x8069D274
#define switchD_ADDR_806a1204 0x806A1204
#define switchD_ADDR_806a14a0 0x806A14A0
#define switchD_ADDR_806a16a4 0x806A16A4
#define switchD_ADDR_806a18e8 0x806A18E8
#define switchD_ADDR_806a1b28 0x806A1B28
#define switchD_ADDR_806a1e04 0x806A1E04
#define switchD_ADDR_806a2658 0x806A2658
#define switchD_ADDR_806a2ea4 0x806A2EA4
#define switchD_ADDR_806a33e0 0x806A33E0
#define switchD_ADDR_806a39c0 0x806A39C0
#define switchD_ADDR_806a3f14 0x806A3F14
#define switchD_ADDR_806a6478 0x806A6478
#define switchD_ADDR_806a6670 0x806A6670
#define switchD_ADDR_806a6868 0x806A6868
#define switchD_ADDR_806a8f9c 0x806A8F9C
#define switchD_ADDR_806b45fc 0x806B45FC
#define switchD_ADDR_806c0740 0x806C0740
#define switchD_ADDR_806c0b00 0x806C0B00
#define switchD_ADDR_806c36c4 0x806C36C4
#define switchD_ADDR_806c4580 0x806C4580
#define switchD_ADDR_806c98fc 0x806C98FC
#define switchD_ADDR_806cc978 0x806CC978
#define switchD_ADDR_806cd084 0x806CD084
#define switchD_ADDR_806cdb50 0x806CDB50
#define nCursorMovementsOnCapSelect_ADDR 0x80751899
#define captainSelectedInd_ADDR 0x807518A8
#define team2CapSelected__ADDR 0x807518A9
#define startPlayingCaptainSelectedSoundInd_ADDR 0x807518AA
#define captainModelsShown_ADDR 0x807518B1
#define loadingNewCaptainModelInd_ADDR 0x807518B2
#define framesOfCursorMovement_ADDR 0x807518B4
#define switchVar_ADDR 0x808E9A4E

// =============================================================================
//  AtGameSettingsScreen-SPECIFIC FUNCTIONS (REL)
// =============================================================================

static inline void bPressOnStadSelectScreen(void) { ((void(*)(void))0x8063F370)(); }
static inline void changeScreenVariables(undefined2 newScreenCode) { ((void(*)(undefined2))0x80640234)(newScreenCode); }
static inline void currentScreenFunctionChooser(void) { ((void(*)(void))0x8064026C)(); }
static inline void stadiumRandomizer(undefined4 lowerBound, undefined4 upperBound) { ((void(*)(undefined4, undefined4))0x8064058C)(lowerBound, upperBound); }
static inline void cursorSndFx(void) { ((void(*)(void))0x80640CC8)(); }
static inline void mainMenuRelated(void) { ((void(*)(void))0x80640FC4)(); }
static inline void mainMenuScreen(void) { ((void(*)(void))0x80641874)(); }
static inline void loadDemoMatch(undefined1 param_1, undefined4 isHumanGame, undefined4 param_3) { ((void(*)(undefined1, undefined4, undefined4))0x80642054)(param_1, isHumanGame, param_3); }
static inline void cssTransitionToNewScreen_(void) { ((void(*)(void))0x806422D0)(); }
static inline void stopShowingCaptainProfile(void) { ((void(*)(void))0x80642664)(); }
static inline void teamReady1(void) { ((void(*)(void))0x806444D8)(); }
static inline void cssChangeScreens(void) { ((void(*)(void))0x80645234)(); }
static inline void cssSelectCPUDifficulty(void) { ((void(*)(void))0x80645518)(); }
static inline void characterSelectScreenControlable(void) { ((void(*)(void))0x8064569C)(); }
static inline void cssUnloadScreen(void) { ((void(*)(void))0x80645DD0)(); }
static inline void cssResetRosterStruct(void) { ((void(*)(void))0x80646598)(); }
static inline void unreferenced_80646dd8(void) { ((void(*)(void))0x80646DD8)(); }
static inline void cssLoadingScreenRelated(void) { ((void(*)(void))0x80646E70)(); }
static inline void copyInfoToInMemRoster(void) { ((void(*)(void))0x806479D4)(); }
static inline void challengeSetRoster(void) { ((void(*)(void))0x8064B024)(); }
static inline void cssReturnToCapSelect_(void) { ((void(*)(void))0x8064BED8)(); }
static inline void characterSelectAPress(undefined4 team) { ((void(*)(undefined4))0x8064D040)(team); }
static inline void characterSelectABDirectionInputs(undefined4 team, enumControllerInput heldButton, enumControllerInput newButton, enumControllerInput processedButton) { ((void(*)(undefined4, enumControllerInput, enumControllerInput, enumControllerInput))0x8064DE28)(team, heldButton, newButton, processedButton); }
static inline void randCharBasedOnClass(undefined4 team) { ((void(*)(undefined4))0x8064E294)(team); }
static inline void randCharacter1(undefined4 team) { ((void(*)(undefined4))0x8064EB34)(team); }
static inline void randCharAlgo2(void) { ((void(*)(void))0x8064ED48)(); }
static inline void randomCharacters(undefined4 team) { ((void(*)(undefined4))0x8064F35C)(team); }
static inline void characterSelectControls(undefined4 playerNumber) { ((void(*)(undefined4))0x8064F590)(playerNumber); }
static inline void teamSelectScreenMain(void) { ((void(*)(void))0x80650144)(); }
static inline void stadiumSelectControls(undefined1 player) { ((void(*)(undefined1))0x806503D4)(player); }
static inline void selectStadiumScreen(void) { ((void(*)(void))0x8065072C)(); }
static inline void challengeCaptainRelated(void) { ((void(*)(void))0x806512CC)(); }
static inline void captainSelectDefaultProcess(void) { ((void(*)(void))0x80651460)(); }
static inline void captainSelectScreen_manager(void) { ((void(*)(void))0x8065201C)(); }
static inline void checkForNewPlayer(void) { ((void(*)(void))0x80653824)(); }
static inline void captainSelect_handleCursor(undefined1 somePlayerNum, undefined4 input_) { ((void(*)(undefined1, undefined4))0x80653D34)(somePlayerNum, input_); }
static inline void loadNewCaptainModelOnCapSelectScreen(undefined4 param_1, undefined4 cursorPos, undefined4 team_, undefined4 always1_) { ((void(*)(undefined4, undefined4, undefined4, undefined4))0x80654198)(param_1, cursorPos, team_, always1_); }
static inline void captainSelect_BPress(undefined1 cursorNumber) { ((void(*)(undefined1))0x80654250)(cursorNumber); }
static inline void captainSelect_APress(undefined1 character) { ((void(*)(undefined1))0x806546A0)(character); }
static inline void captainSelectScreenInputs(undefined4 playerNum, enumControllerInput heldInput, enumControllerInput newInput_, enumControllerInput processedInput_) { ((void(*)(undefined4, enumControllerInput, enumControllerInput, enumControllerInput))0x80654B90)(playerNum, heldInput, newInput_, processedInput_); }
static inline void captainSelect_handleInputs(undefined4 playerNum) { ((void(*)(undefined4))0x80654F14)(playerNum); }
static inline void onlySetPort1ToActiveOnInitialCapSSLoad(void) { ((void(*)(void))0x806554B0)(); }
static inline void set807518de(undefined4 team, undefined1 always1_) { ((void(*)(undefined4, undefined1))0x80655ADC)(team, always1_); }
static inline void captainSelectLoadScreen(void) { ((void(*)(void))0x80658050)(); }
static inline void optionsScreen_80658d98(void) { ((void(*)(void))0x80658D98)(); }
static inline void settingValuesTo0(void) { ((void(*)(void))0x80658FC0)(); }
static inline void challengeFileSelect_80659248(void) { ((void(*)(void))0x80659248)(); }
static inline void challengeMap_8069249c(void) { ((void(*)(void))0x8069249C)(); }
static inline void recordsScreen_8069d198(void) { ((void(*)(void))0x8069D198)(); }
static inline void cssCheckSomethingAboutCharacters(void) { ((void(*)(void))0x806B16F0)(); }
static inline void gfx_cssCharStatBars_sthgElse(undefined4 gfxPointer, undefined4 team) { ((void(*)(undefined4, undefined4))0x806B3FD4)(gfxPointer, team); }
static inline void teamSelectionSetChemStars(undefined4 param_1, undefined4 team) { ((void(*)(undefined4, undefined4))0x806B4C78)(param_1, team); }
static inline void removeAllPlayersFromTeam(undefined4 gfxPtr, undefined4 team) { ((void(*)(undefined4, undefined4))0x806B6734)(gfxPtr, team); }
static inline void cssAction_0x1d(void) { ((void(*)(void))0x806B70F0)(); }
static inline void cssAction_0x1c(void) { ((void(*)(void))0x806B7400)(); }
static inline void cssAction_0x1b(void) { ((void(*)(void))0x806B7B54)(); }
static inline void cssAction_0x1a(void) { ((void(*)(void))0x806B800C)(); }
static inline void cssAction_0x19(void) { ((void(*)(void))0x806B81C0)(); }
static inline void cssAction_0x18(void) { ((void(*)(void))0x806B8428)(); }
static inline void randomTeamMemberSelection(void) { ((void(*)(void))0x806B89C4)(); }
static inline void cssAction_case9(void) { ((void(*)(void))0x806BB08C)(); }
static inline void cssUnready(void) { ((void(*)(void))0x806BD414)(); }
static inline void cssReady(maybeGraphicsManager * param_1, undefined4 team) { ((void(*)(maybeGraphicsManager *, undefined4))0x806BDA08)(param_1, team); }
static inline void cssRemoveCharacter2(void) { ((void(*)(void))0x806BE0C4)(); }
static inline void cssRemoveCharacter1(undefined4 param_1, undefined4 team, undefined4 param_3, undefined4 param_4, undefined4 param_5) { ((void(*)(undefined4, undefined4, undefined4, undefined4, undefined4))0x806BE350)(param_1, team, param_3, param_4, param_5); }
static inline void cssSelectCharacter(int gfxPointer, int team, undefined4 param_3, undefined4 param_4, char positionNum) { ((void(*)(int, int, undefined4, undefined4, char))0x806BE950)(gfxPointer, team, param_3, param_4, positionNum); }
static inline void captainSelectUnloadCSSLoadRelated(undefined4 param_1, undefined4 index_) { ((void(*)(undefined4, undefined4))0x806BF144)(param_1, index_); }
static inline void maybeBackgroundImagesForCaptain(void) { ((void(*)(void))0x806BFFF0)(); }
static inline void cssActions(void * param_1, void * param_2, undefined4 param_3, undefined4 param_4, undefined1 param_5) { ((void(*)(void *, void *, undefined4, undefined4, undefined1))0x806C06BC)(param_1, param_2, param_3, param_4, param_5); }
static inline void relatedToTeamSelection3(void) { ((void(*)(void))0x806C1830)(); }
static inline void relatedToTeamSelection4(void) { ((void(*)(void))0x806C1EEC)(); }
static inline void stadiumRandomRelated(void) { ((void(*)(void))0x806C2BC8)(); }
static inline void unreferenced_806c341c(void) { ((void(*)(void))0x806C341C)(); }
static inline void stadiumScreenAnimations_(void) { ((void(*)(void))0x806C403C)(); }
static inline void loadStadiumScreen_(void) { ((void(*)(void))0x806C419C)(); }
static inline void unreferenced_806c423c(void) { ((void(*)(void))0x806C423C)(); }
static inline void titleScreen_806cdf5c(void) { ((void(*)(void))0x806CDF5C)(); }

